const ROLE_NAMES = {
  ADMIN: 'ADMIN',
  MAKER: 'MAKER',
  CHECKER: 'CHECKER',
  EXECUTOR: 'EXECUTOR',
};

const TOKEN_REQUEST_TYPES = {
  MINT: 'MINT',
  TRANSFER: 'TRANSFER',
  BURN: 'BURN',
};

const TOKEN_REQUEST_STATUSES = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  READY_FOR_EXECUTION: 'READY_FOR_EXECUTION',
  ON_CHAIN_PENDING: 'ON_CHAIN_PENDING',
  EXECUTED: 'EXECUTED',
  FAILED: 'FAILED',
};

const EXECUTION_MODES = {
  SERVER_MANAGED: 'SERVER_MANAGED',
  BROWSER_WALLET: 'BROWSER_WALLET',
};

const APPROVAL_ACTIONS = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
};

const AUDIT_ENTITY_TYPES = {
  USER: 'USER',
  ROLE_ASSIGNMENT: 'ROLE_ASSIGNMENT',
  WALLET: 'WALLET',
  TOKEN_REQUEST: 'TOKEN_REQUEST',
  MANAGED_TOKEN: 'MANAGED_TOKEN',
};

const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  SUBMIT: 'SUBMIT',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  MARK_READY: 'MARK_READY',
  PREPARE_EXECUTION: 'PREPARE_EXECUTION',
  RECORD_INITIATION: 'RECORD_INITIATION',
  RECORD_EXECUTION: 'RECORD_EXECUTION',
  STATUS_CHANGE: 'STATUS_CHANGE',
  ASSIGN_ROLE: 'ASSIGN_ROLE',
};

const VALID_STATUS_TRANSITIONS = {
  [TOKEN_REQUEST_STATUSES.DRAFT]: [TOKEN_REQUEST_STATUSES.PENDING_APPROVAL],
  [TOKEN_REQUEST_STATUSES.PENDING_APPROVAL]: [
    TOKEN_REQUEST_STATUSES.APPROVED,
    TOKEN_REQUEST_STATUSES.READY_FOR_EXECUTION,
    TOKEN_REQUEST_STATUSES.ON_CHAIN_PENDING,
    TOKEN_REQUEST_STATUSES.REJECTED,
  ],
  [TOKEN_REQUEST_STATUSES.APPROVED]: [
    TOKEN_REQUEST_STATUSES.READY_FOR_EXECUTION,
    TOKEN_REQUEST_STATUSES.ON_CHAIN_PENDING,
  ],
  [TOKEN_REQUEST_STATUSES.READY_FOR_EXECUTION]: [
    TOKEN_REQUEST_STATUSES.EXECUTED,
    TOKEN_REQUEST_STATUSES.FAILED,
  ],
  [TOKEN_REQUEST_STATUSES.ON_CHAIN_PENDING]: [
    TOKEN_REQUEST_STATUSES.EXECUTED,
    TOKEN_REQUEST_STATUSES.FAILED,
  ],
  [TOKEN_REQUEST_STATUSES.REJECTED]: [],
  [TOKEN_REQUEST_STATUSES.EXECUTED]: [],
  [TOKEN_REQUEST_STATUSES.FAILED]: [],
};

module.exports = {
  ROLE_NAMES,
  TOKEN_REQUEST_TYPES,
  TOKEN_REQUEST_STATUSES,
  EXECUTION_MODES,
  APPROVAL_ACTIONS,
  AUDIT_ENTITY_TYPES,
  AUDIT_ACTIONS,
  VALID_STATUS_TRANSITIONS,
};
